export const COMPONENT_ID = 'COMPONENT_ID';
export const GET_TIMESHEET_TYPES = 'GET_TIMESHEETS';
export const TIMESHEET_SET_DATA = 'STORE_TIMESHEETS';
export const GET_TIMESHEET_DATA = 'GET_TIMESHEET_DATA'